module.exports = { 
  "inset": "var(--shadow-inset)",
  "inset-button-pressed": "var(--shadow-inset-button-pressed)",
  "inset-button": "var(--shadow-inset-button)",
  "button": "var(--shadow-button)",
  "modal": "var(--shadow-modal)",
  "layer": "var(--shadow-layer)",
  "popover": "var(--shadow-popover)",
  "card": "var(--shadow-card)",
  "top-bar": "var(--shadow-top-bar)",
  "deep": "var(--shadow-deep)",
  "base": "var(--shadow-base)",
  "faint": "var(--shadow-faint)",
  "transparent": "var(--shadow-transparent)",
  "xs": "var(--shadow-xs)",
  "sm": "var(--shadow-sm)",
  "md": "var(--shadow-md)",
  "lg": "var(--shadow-lg)",
  "xl": "var(--shadow-xl)",
  "2xl": "var(--shadow-2xl)",
}
