module.exports = { 
  "shadowModal": "var(--shadow-modal)",
  "shadowLayer": "var(--shadow-layer)",
  "insetBasic": "var(--shadow-inset-basic)",
  "insetButton": "var(--shadow-inset-button)",
  "buttonPressed": "var(--shadow-button-pressed)",
  "buttonDefault": "var(--shadow-button-default)",
  "basicDeep": "var(--shadow-basic-deep)",
  "basicFaint": "var(--shadow-basic-faint)",
  "basicTransparent": "var(--shadow-basic-transparent)",
  "basicXs": "var(--shadow-basic-xs)",
  "basicSm": "var(--shadow-basic-sm)",
  "basicMd": "var(--shadow-basic-md)",
  "basicLg": "var(--shadow-basic-lg)",
  "basicXl": "var(--shadow-basic-xl)",
  "basic2xl": "var(--shadow-basic-2xl)",
  "elementPopover": "var(--shadow-element-popover)",
  "elementCard": "var(--shadow-element-card)",
  "elementTopNav": "var(--shadow-element-topnav)",
  "elementFocus": "var(--shadow-element-focus)",
}
