import {
  IconArrowLeft,
  IconArrowRight,
  IconBarrierBlock,
  IconBellFilled,
  IconCircleCheckFilled,
  IconCloudUpload,
  IconDatabase,
  IconDatabaseCog,
  IconDatabasePlus,
  IconFilePlus,
  IconFolder,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLink,
  IconSearch,
  IconTrash,
  IconUserCog,
  // TablerIconsProps,
} from '@tabler/icons-react';

export const Icons = {
  back: IconArrowLeft,
  logo: IconFolder,
  datasetSettings: IconDatabaseCog,
  dataset: IconDatabase,
  addDataset: IconDatabasePlus,
  userSettings: IconUserCog,
  arrowRight: IconArrowRight,
  search: IconSearch,
  notification: IconBellFilled,

  construction: IconBarrierBlock,
  link: IconLink,
  collapse: IconLayoutSidebarLeftCollapse,
  expand: IconLayoutSidebarLeftExpand,
  distribution: IconFilePlus,
  dropzone: IconCloudUpload,
  check: IconCircleCheckFilled,
  delete: IconTrash,
};
